repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
